/**
 * Source Monitor Agent — deterministic unit tests
 *
 * Test runner: node:test (tsx --test)
 * All tests use local fixtures only. Zero network calls. Zero dynamic dates.
 * Frozen dates: from=2026-06-10, to=2026-06-17 (generated by snapshot-writer CLI)
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, rmSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { monitorSource, SourceMonitorError } from '../../src/agents/source-monitor.js';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');

const FROZEN_SOURCE = 'infoleg';
const FROM_DATE = '2026-06-10';
const TO_DATE = '2026-06-17';

const FROM_SNAP_PATH = resolve(repoRoot, 'data', 'sources', FROZEN_SOURCE, `${FROM_DATE}.json`);
const TO_SNAP_PATH = resolve(repoRoot, 'data', 'sources', FROZEN_SOURCE, `${TO_DATE}.json`);
const DELTA_OUTPUT_DIR = resolve(repoRoot, 'data', 'deltas', FROZEN_SOURCE);
const DELTA_OUTPUT_PATH = resolve(DELTA_OUTPUT_DIR, `${FROM_DATE}_to_${TO_DATE}.json`);

const TEST_SOURCE = '__test_source_monitor__';
const TEST_SNAP_DIR = resolve(repoRoot, 'data', 'sources', TEST_SOURCE);
const TEST_DELTA_DIR = resolve(repoRoot, 'data', 'deltas', TEST_SOURCE);

// ---------------------------------------------------------------------------
// Minimal valid snapshot factory (no dynamic dates — all frozen)
// ---------------------------------------------------------------------------

function makeSnapshot(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    snapshot_id: `${TEST_SOURCE}--2026-01-01`,
    source_id: TEST_SOURCE,
    source_locator: `data/fixtures/${TEST_SOURCE}-sample.json`,
    captured_at: '2026-01-01T00:00:00.000Z',
    capture_method: 'local_fixture',
    freshness_status: 'current',
    review_status: 'not_reviewed',
    extraction_status: 'not_started',
    human_review_required: true,
    downstream_allowed: false,
    schema_version: '1.0.0',
    ...overrides,
  };
}

function writeTestSnapshot(date: string, snap: Record<string, unknown>): string {
  const p = resolve(TEST_SNAP_DIR, `${date}.json`);
  writeFileSync(p, JSON.stringify(snap, null, 2) + '\n', 'utf-8');
  return p;
}

// ---------------------------------------------------------------------------
// Setup / Teardown
// ---------------------------------------------------------------------------

before(() => {
  mkdirSync(TEST_SNAP_DIR, { recursive: true });
  mkdirSync(TEST_DELTA_DIR, { recursive: true });
});

after(() => {
  rmSync(TEST_SNAP_DIR, { recursive: true, force: true });
  rmSync(TEST_DELTA_DIR, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// Happy Path — real infoleg snapshots (generated by snapshot-writer CLI)
// ---------------------------------------------------------------------------

describe('monitorSource — happy path (real infoleg snapshots)', () => {
  it('requires both snapshot files to exist as precondition', () => {
    assert.equal(existsSync(FROM_SNAP_PATH), true, `Missing fixture: ${FROM_SNAP_PATH}`);
    assert.equal(existsSync(TO_SNAP_PATH), true, `Missing fixture: ${TO_SNAP_PATH}`);
  });

  it('writes delta file at expected path', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });
    assert.equal(result.output_path, DELTA_OUTPUT_PATH);
    assert.equal(existsSync(DELTA_OUTPUT_PATH), true);
  });

  it('returns schema_valid: true', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });
    assert.equal(result.schema_valid, true);
  });

  it('detects content_hash_changed (v1 vs v2 have different fixtures)', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });
    assert.equal(result.delta.content_hash_changed, true);
  });

  it('uses content diff_mode (both snapshots have content field)', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });
    assert.equal(result.delta.diff_mode, 'content');
  });

  it('detects at least one change between v1 and v2', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });
    assert.ok(result.delta.summary.total > 0, 'Expected at least one change between v1 and v2 fixtures');
  });

  it('sets governance fields to safe defaults', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });
    assert.equal(result.delta.human_review_required, true);
    assert.equal(result.delta.downstream_allowed, false);
  });

  it('summary counts are consistent with changes array', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });
    const { changes, summary } = result.delta;
    assert.equal(summary.added, changes.filter(c => c.type === 'added').length);
    assert.equal(summary.removed, changes.filter(c => c.type === 'removed').length);
    assert.equal(summary.modified, changes.filter(c => c.type === 'modified').length);
    assert.equal(summary.total, changes.length);
  });
});

// ---------------------------------------------------------------------------
// Identical snapshots — no changes
// ---------------------------------------------------------------------------

describe('monitorSource — identical snapshots', () => {
  it('produces empty changes array and content_hash_changed: false', async () => {
    const snap = makeSnapshot({
      content: { key: 'value', items: [1, 2, 3] },
      content_hash: 'sha256:' + 'a'.repeat(64),
    });
    writeTestSnapshot('2026-02-01', snap);
    writeTestSnapshot('2026-02-02', snap);

    const result = await monitorSource({
      source_id: TEST_SOURCE,
      from_date: '2026-02-01',
      to_date: '2026-02-02',
      from_snapshot_path: resolve(TEST_SNAP_DIR, '2026-02-01.json'),
      to_snapshot_path: resolve(TEST_SNAP_DIR, '2026-02-02.json'),
    });

    assert.equal(result.delta.changes.length, 0);
    assert.equal(result.delta.summary.total, 0);
    assert.equal(result.delta.content_hash_changed, false);
  });
});

// ---------------------------------------------------------------------------
// Validation failures
// ---------------------------------------------------------------------------

describe('monitorSource — from_date >= to_date', () => {
  it('throws DATE_ORDER_ERROR when from_date equals to_date', async () => {
    await assert.rejects(
      () => monitorSource({ source_id: TEST_SOURCE, from_date: '2026-03-01', to_date: '2026-03-01' }),
      (err: unknown) => {
        assert.ok(err instanceof SourceMonitorError);
        assert.equal(err.code, 'DATE_ORDER_ERROR');
        return true;
      }
    );
  });

  it('throws DATE_ORDER_ERROR when from_date is after to_date', async () => {
    await assert.rejects(
      () => monitorSource({ source_id: TEST_SOURCE, from_date: '2026-04-02', to_date: '2026-04-01' }),
      (err: unknown) => {
        assert.ok(err instanceof SourceMonitorError);
        assert.equal(err.code, 'DATE_ORDER_ERROR');
        return true;
      }
    );
  });
});

describe('monitorSource — source_id mismatch', () => {
  it('throws SOURCE_ID_MISMATCH when snapshots have different source_ids', async () => {
    const snapA = makeSnapshot({ source_id: TEST_SOURCE, snapshot_id: `${TEST_SOURCE}--2026-05-01` });
    const snapB = makeSnapshot({ source_id: 'other-source', snapshot_id: 'other-source--2026-05-02', source_locator: 'data/fixtures/other-source-sample.json' });

    writeTestSnapshot('2026-05-01', snapA);
    writeTestSnapshot('2026-05-02', snapB);

    await assert.rejects(
      () => monitorSource({
        source_id: TEST_SOURCE,
        from_date: '2026-05-01',
        to_date: '2026-05-02',
        from_snapshot_path: resolve(TEST_SNAP_DIR, '2026-05-01.json'),
        to_snapshot_path: resolve(TEST_SNAP_DIR, '2026-05-02.json'),
      }),
      (err: unknown) => {
        assert.ok(err instanceof SourceMonitorError);
        assert.equal(err.code, 'SOURCE_ID_MISMATCH');
        return true;
      }
    );
  });

  it('does not write any delta file on SOURCE_ID_MISMATCH', async () => {
    const badDelta = resolve(TEST_DELTA_DIR, '2026-05-01_to_2026-05-02.json');
    try {
      await monitorSource({
        source_id: TEST_SOURCE,
        from_date: '2026-05-01',
        to_date: '2026-05-02',
        from_snapshot_path: resolve(TEST_SNAP_DIR, '2026-05-01.json'),
        to_snapshot_path: resolve(TEST_SNAP_DIR, '2026-05-02.json'),
      });
    } catch {
      // expected
    }
    assert.equal(existsSync(badDelta), false);
  });
});

describe('monitorSource — missing snapshot file', () => {
  it('throws SNAPSHOT_NOT_FOUND for missing from snapshot', async () => {
    await assert.rejects(
      () => monitorSource({
        source_id: TEST_SOURCE,
        from_date: '2026-06-01',
        to_date: '2026-06-02',
        from_snapshot_path: '/nonexistent/from.json',
        to_snapshot_path: '/nonexistent/to.json',
      }),
      (err: unknown) => {
        assert.ok(err instanceof SourceMonitorError);
        assert.equal(err.code, 'SNAPSHOT_NOT_FOUND');
        return true;
      }
    );
  });
});

// ---------------------------------------------------------------------------
// Legacy snapshot (missing content field)
// ---------------------------------------------------------------------------

describe('monitorSource — legacy snapshot without content field', () => {
  it('uses full_object diff_mode when content field is absent', async () => {
    const legacyFrom = makeSnapshot({
      snapshot_id: `${TEST_SOURCE}--2026-07-01`,
      content_hash: 'sha256:' + 'b'.repeat(64),
      source_version_label: 'v1.0',
    });
    const legacyTo = makeSnapshot({
      snapshot_id: `${TEST_SOURCE}--2026-07-02`,
      content_hash: 'sha256:' + 'c'.repeat(64),
      source_version_label: 'v2.0',
    });

    writeTestSnapshot('2026-07-01', legacyFrom);
    writeTestSnapshot('2026-07-02', legacyTo);

    const result = await monitorSource({
      source_id: TEST_SOURCE,
      from_date: '2026-07-01',
      to_date: '2026-07-02',
      from_snapshot_path: resolve(TEST_SNAP_DIR, '2026-07-01.json'),
      to_snapshot_path: resolve(TEST_SNAP_DIR, '2026-07-02.json'),
    });

    assert.equal(result.delta.diff_mode, 'full_object');
    assert.equal(result.schema_valid, true);
  });

  it('detects changed field in full_object diff', async () => {
    const result = await monitorSource({
      source_id: TEST_SOURCE,
      from_date: '2026-07-01',
      to_date: '2026-07-02',
      from_snapshot_path: resolve(TEST_SNAP_DIR, '2026-07-01.json'),
      to_snapshot_path: resolve(TEST_SNAP_DIR, '2026-07-02.json'),
    });

    // source_version_label changed from v1.0 to v2.0 — should appear in changes
    const versionChange = result.delta.changes.find(c => c.path.includes('source_version_label'));
    assert.ok(versionChange !== undefined, 'Expected source_version_label change in full_object diff');
    assert.equal(versionChange.type, 'modified');
    assert.equal(versionChange.old_value, 'v1.0');
    assert.equal(versionChange.new_value, 'v2.0');
  });

  it('notes warns about missing content field', async () => {
    const result = await monitorSource({
      source_id: TEST_SOURCE,
      from_date: '2026-07-01',
      to_date: '2026-07-02',
      from_snapshot_path: resolve(TEST_SNAP_DIR, '2026-07-01.json'),
      to_snapshot_path: resolve(TEST_SNAP_DIR, '2026-07-02.json'),
    });

    assert.ok(result.delta.notes.length > 0, 'Expected warning note about missing content field');
  });
});

// ---------------------------------------------------------------------------
// Schema compliance
// ---------------------------------------------------------------------------

describe('monitorSource — delta schema compliance', () => {
  it('written delta file contains all required top-level fields', async () => {
    const snap1 = makeSnapshot({
      content: { a: 1 },
      content_hash: 'sha256:' + 'd'.repeat(64),
    });
    const snap2 = makeSnapshot({
      snapshot_id: `${TEST_SOURCE}--2026-08-02`,
      content: { a: 2 },
      content_hash: 'sha256:' + 'e'.repeat(64),
    });

    writeTestSnapshot('2026-08-01', snap1);
    writeTestSnapshot('2026-08-02', snap2);

    const result = await monitorSource({
      source_id: TEST_SOURCE,
      from_date: '2026-08-01',
      to_date: '2026-08-02',
      from_snapshot_path: resolve(TEST_SNAP_DIR, '2026-08-01.json'),
      to_snapshot_path: resolve(TEST_SNAP_DIR, '2026-08-02.json'),
    });

    const parsed = JSON.parse(readFileSync(result.output_path, 'utf-8')) as Record<string, unknown>;
    const required = ['delta_id', 'source_id', 'from_snapshot', 'to_snapshot',
      'from_date', 'to_date', 'content_hash_changed', 'diff_mode',
      'changes', 'summary', 'human_review_required', 'downstream_allowed', 'schema_version'];

    for (const field of required) {
      assert.ok(field in parsed, `Missing required field: ${field}`);
    }
  });

  it('change paths follow RFC 6901 style (start with /)', async () => {
    const result = await monitorSource({
      source_id: FROZEN_SOURCE,
      from_date: FROM_DATE,
      to_date: TO_DATE,
    });

    for (const change of result.delta.changes) {
      assert.ok(
        change.path.startsWith('/'),
        `Change path should start with /: "${change.path}"`
      );
    }
  });
});
