import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import type { CapabilityRequest } from '../../src/capabilities/index.js';
import type { ExecutionProfile } from '../../src/execution/execution-profile.js';
import { MultiProviderGateway } from '../../src/execution/multi-provider-gateway.js';
import { ProviderAdapterRegistry } from '../../src/providers/adapter-registry.js';
import type { ProviderAdapter } from '../../src/providers/provider-adapter.js';
import { ReplayProviderAdapter } from '../../src/providers/replay-adapter.js';
import { BudgetEnforcer, InMemoryBudgetLedger } from '../../src/governance/index.js';
import { LOCAL_REPLAY_PRIVACY } from '../helpers/privacy.js';

const request: CapabilityRequest = { request_id: 'request-replay-001', capability_id: 'evidence.extraction.normative_claims' as never, schema_version: '1.0.0', input: { packet_id: 'packet-replay-001', evidence_refs: [{ source_id: 'source-001', snapshot_id: 'snapshot-001', section_label: 'section-1', excerpt: 'Synthetic evidence only.' }] }, context: { data_classification: 'public' } };
const baseProfile: ExecutionProfile = { profile_id: 'test.replay' as never, capability_id: request.capability_id, provider_id: 'replay' as never, model_id: 'fixture' as never, mode: 'replay', lifecycle_status: 'candidate', enabled: true, contract_version: '1.0.0', configuration: { timeout_ms: 1000, response_format: 'json' }, eligibility: { privacy_compatibility: 'declared_not_enforced', budget_class: 'development', evaluation_status: 'fixture_verified' }, privacy: LOCAL_REPLAY_PRIVACY, fixture_id: 'normative-claims-success' };
function gateway(profile = baseProfile, adapter: ProviderAdapter = new ReplayProviderAdapter()) { const registry = new ProviderAdapterRegistry(); registry.registerProviderAdapter(adapter); return new MultiProviderGateway({ registry, profileResolver: () => profile, clock: (() => { let n = 0; return () => new Date(n++ * 10); })(), executionId: () => 'execution-001', budgetEnforcer: new BudgetEnforcer({ ledger: new InMemoryBudgetLedger() }) }); }

describe('AI-72 multi-provider gateway', () => {
  it('fails closed for an unknown explicit profile ID', async () => { const registry = new ProviderAdapterRegistry(); registry.registerProviderAdapter(new ReplayProviderAdapter()); const outcome = await new MultiProviderGateway({ registry, clock: () => new Date(0), executionId: () => 'execution-unknown' }).execute({ capability_request: request, execution_profile_id: 'missing.profile' }); assert.equal(outcome.audit.error_code, 'UNKNOWN_PROFILE'); assert.equal(outcome.result.status, 'blocked'); });
  it('executes deterministic replay and strips adapter metadata', async () => { const a = await gateway().execute({ capability_request: request, execution_profile_id: 'test.replay' }); const b = await gateway().execute({ capability_request: request, execution_profile_id: 'test.replay' }); assert.deepEqual(a, b); assert.equal(a.result.status, 'succeeded'); const serialized = JSON.stringify(a.result); assert.doesNotMatch(serialized, /provider_id|model_id|dashscope|qwen/); assert.equal(a.result.governance.downstream_allowed, false); });
  it('fails closed for disabled, retired, mismatched, and unknown-provider profiles', async () => { const variants: Array<[Partial<ExecutionProfile>, string]> = [[{ enabled: false }, 'PROFILE_DISABLED'], [{ lifecycle_status: 'retired' }, 'PROFILE_RETIRED'], [{ capability_id: 'review.human.gate' as never }, 'PROFILE_CAPABILITY_MISMATCH'], [{ provider_id: 'missing' as never }, 'UNKNOWN_PROVIDER']]; for (const [change, code] of variants) { const outcome = await gateway({ ...baseProfile, ...change }).execute({ capability_request: request, execution_profile_id: 'x' }); assert.equal(outcome.audit.error_code, code); assert.notEqual(outcome.result.status, 'succeeded'); } });
  it('enforces an optional exact profile contract version before privacy, budget, or adapter execution', async () => { let privacyCalls = 0; let budgetCalls = 0; let adapterCalls = 0; const registry = new ProviderAdapterRegistry(); registry.registerProviderAdapter({ provider_id: 'replay' as never, supports: () => true, execute: async () => { adapterCalls++; throw new Error('must not execute'); } }); const exactGateway = new MultiProviderGateway({ registry, profileResolver: () => baseProfile, clock: () => new Date(0), executionId: () => 'execution-version', privacyEnforcer: { enforce: () => { privacyCalls++; throw new Error('must not enforce privacy'); } } as never, budgetEnforcer: { reserve: () => { budgetCalls++; throw new Error('must not reserve'); } } as never }); const mismatch = await exactGateway.execute({ capability_request: request, execution_profile_id: 'test.replay', expected_profile_contract_version: '1.1.0' }); assert.equal(mismatch.audit.error_code, 'EXECUTION_PROFILE_VERSION_MISMATCH'); assert.equal(mismatch.result.status, 'blocked'); assert.equal(privacyCalls, 0); assert.equal(budgetCalls, 0); assert.equal(adapterCalls, 0); const matching = await gateway().execute({ capability_request: request, execution_profile_id: 'test.replay', expected_profile_contract_version: '1.0.0' }); assert.equal(matching.result.status, 'succeeded'); const legacy = await gateway().execute({ capability_request: request, execution_profile_id: 'test.replay' }); assert.equal(legacy.result.status, 'succeeded'); });
  it('normalizes malformed, timeout, provider-error, and blocked fixtures', async () => { for (const [fixture, code] of [['malformed-response','PROVIDER_RESPONSE_INVALID'],['timeout','PROVIDER_TIMEOUT'],['provider-error','PROVIDER_UNAVAILABLE'],['blocked','PROVIDER_RESPONSE_INVALID']] as const) { const outcome = await gateway({ ...baseProfile, fixture_id: fixture }).execute({ capability_request: request, execution_profile_id: 'x' }); assert.equal(outcome.audit.error_code, code); assert.notEqual(outcome.result.status, 'succeeded'); } });
  it('calls exactly one explicit adapter with no retry, fallback, ranking, or shadow execution', async () => { let calls = 0; const adapter: ProviderAdapter = { provider_id: 'counting' as never, supports: () => true, execute: async () => { calls += 1; throw new Error('unsafe provider detail'); } }; const outcome = await gateway({ ...baseProfile, provider_id: adapter.provider_id }, adapter).execute({ capability_request: request, execution_profile_id: 'explicit' }); assert.equal(calls, 1); assert.equal(outcome.audit.error_code, 'PROVIDER_UNAVAILABLE'); assert.doesNotMatch(JSON.stringify(outcome), /unsafe provider detail/); });
  it('keeps audit records metadata-only', async () => { const outcome = await gateway().execute({ capability_request: request, execution_profile_id: 'test.replay' }); const audit = JSON.stringify(outcome.audit); assert.doesNotMatch(audit, /Synthetic evidence|messages|prompt|content|reviewer|api_key|raw/i); });
});
