import assert from 'node:assert/strict'; import { describe, it } from 'node:test';
import { calculateCost, GovernanceError, normalizeUsage, PricingCatalog, type NormalizedUsage, type PricingEntry } from '../../src/governance/index.js';
const price: PricingEntry = { pricing_id:'p',schema_version:'1',provider_id:'replay',model_id:'m',currency:'USD',input_price_minor:3,output_price_minor:7,cached_input_price_minor:1,reasoning_price_minor:11,pricing_denominator_tokens:1000,effective_from:'2020-01-01T00:00:00Z',evidence_status:'fixture',permitted_execution_modes:['replay'],evidence_ref:'repo:test' };
const usage = (overrides: Partial<NormalizedUsage> = {}): NormalizedUsage => ({input_tokens:1000,output_tokens:1000,total_tokens:2000,request_count:1,source:'estimated',status:'complete',confidence:'high',...overrides});
describe('AI-74 usage and exact cost',()=>{
  it('normalizes provider, unavailable, and synthetic fixture usage without converting unknowns to zero',()=>{ assert.equal(normalizeUsage({input_tokens:1,output_tokens:2,total_tokens:3}).source,'provider_reported'); assert.equal(normalizeUsage(undefined).input_tokens,undefined); assert.equal(normalizeUsage({input_tokens:1,output_tokens:2,total_tokens:3,source:'fixture',fixture_origin:'synthetic'}).fixture_origin,'synthetic'); });
  it('rejects negative, fractional, overflow, and inconsistent usage',()=>{ for(const value of [-1,1.2,Number.MAX_SAFE_INTEGER+1]) assert.throws(()=>normalizeUsage({input_tokens:value}),GovernanceError); assert.throws(()=>normalizeUsage({input_tokens:1,output_tokens:2,total_tokens:4}),GovernanceError); });
  it('keeps estimates and actual provider usage distinct',()=>{ assert.notEqual(usage().source,normalizeUsage({input_tokens:2,output_tokens:3,total_tokens:5}).source); });
  it('calculates differing input/output prices with exact integer ceiling',()=>{ const c=calculateCost(usage(),price,'estimated'); assert.equal(c.input_cost_minor,3n); assert.equal(c.output_cost_minor,7n); assert.equal(c.total_cost_minor,10n); });
  it('supports cached and reasoning prices',()=>{ const c=calculateCost(usage({cached_input_tokens:500,reasoning_tokens:250}),price,'actual'); assert.deepEqual([c.input_cost_minor,c.cached_input_cost_minor,c.output_cost_minor,c.reasoning_cost_minor,c.total_cost_minor],[2n,1n,6n,3n,12n]); });
  it('has no floating point drift and fails overflow closed',()=>{ assert.equal(calculateCost(usage({input_tokens:1,output_tokens:1,total_tokens:2}),price,'estimated').total_cost_minor,2n); assert.throws(()=>calculateCost(usage(),{...price,input_price_minor:Number.MAX_SAFE_INTEGER,output_price_minor:Number.MAX_SAFE_INTEGER},'actual'),GovernanceError); });
  it('blocks missing, ambiguous, expired, and required-unverified pricing',()=>{ const profile={provider_id:'x',model_id:'m',mode:'replay'} as never; assert.throws(()=>new PricingCatalog({schema_version:'1',prices:[]}).resolve(profile,new Date(),false),/governance/); const base={...price,provider_id:'x'}; assert.throws(()=>new PricingCatalog({schema_version:'1',prices:[base,{...base,pricing_id:'q'}]}).resolve(profile,new Date(),false),GovernanceError); assert.throws(()=>new PricingCatalog({schema_version:'1',prices:[{...base,expires_at:'2021-01-01T00:00:00Z'}]}).resolve(profile,new Date('2022-01-01'),false),GovernanceError); assert.throws(()=>new PricingCatalog({schema_version:'1',prices:[{...base,evidence_status:'unknown'}]}).resolve(profile,new Date('2022-01-01'),true),GovernanceError); });
});
